file validation changes

diff --git a/Script1/script2 b/Script1/script2
--- a/Script1/script2
+++ b/Script1/script2
@@ -70,6 +70,17 @@ function private_download() {
 
 private_download
 
+function validate() {
+  if [ -d "$SAVE_PATH" ]; then
+      echo "File Downloaded."
+  else
+      echo "Failed to download"
+      exit 1
+  fi
+ }
+
+ validate
+
 #echo "please enter file path to dockerfile"
 #read -r "DOCKER_FILE"
 
@@ -79,10 +90,8 @@ function docker_create() {
     if [ "$(command docker ps)" ]; then
         echo "Docker is running"
         cd "$DOCKER_FILE" || exit 1
-        #/usr/local/bin/docker import "$DOCKER_PATH" "$IMAGE_NAME" | 
         /usr/local/bin/docker build "$DOCKER_FILE" || exit 1
         /usr/local/bin/docker build . -t "$IMAGE_NAME"
-         #| /usr/local/bin/docker run $IMAGE_NAME" || exit 1
     else 
         echo "Docker is not running or not installed"
         exit 1
@@ -107,7 +116,7 @@ function Kubernetes_create() {
     if [ "$(command kubectl version --output=yaml)" ]; then
         echo "Kubernetes is installed"
         cd "$K8_PATH" || exit 1
-        kubectl apply -f "$FILE_POD"
+        kubectl apply -f "$FILE_POD" 
         kubectl describe pod "$POD_NAME"
     else
         echo "Kubernetes pod or deployment not found"
@@ -118,10 +127,9 @@ function Kubernetes_create() {
 
 Kubernetes_create
 
-Deployment="nginx-deployment"
 IMAGE_NAME="my_image"
 
-#echo "please provide the deployment or pod name to be patched"
+#echo "please provide the pod name to be patched"
 #read -r Deployment
 
 #echo "please enter name of patch file"
@@ -129,31 +137,21 @@ IMAGE_NAME="my_image"
 
 
 function Kubernetes_patch() {
-    if [ "$(command kubectl get pods)" ]; then
-        echo "Pod found"
+    if [ "$(command kubectl get pods $POD_NAME)" ]; then
+        echo "Pod found" 
         cd "$K8_PATH" || exit 1
-        #kubectl patch pod "$Deployment" --patch-file "$FILE_NAME" || kubectl patch pod "$Deployment" --patch-file "$FILE_NAME"
-        kubectl patch pod "$POD_NAME" --type='json' -p=' [{"op": "replace", "path": "/spec/containers/0/image", "value":"my_image"}]' #kubectl patch deployment "$Deployment" --subresource='image' --type='merge' -p '{"spec/containers/":{"image":my_image}}'
+        kubectl patch pod "$POD_NAME" --type='json' -p=' [{"op": "replace", "path": "/spec/containers/0/image", "value":"my_image"}]'
         kubectl describe pod "$POD_NAME"
     else
         echo "Pod not found"
-        kubectl delete pod "$POD_NAME" || kubectl delete deployment "$Deployment"
-        echo "Pod or deployment deleted"
+        kubectl delete pod "$POD_NAME" || kubectl delete deployment "$POD_NAME"
+        echo "Pod deleted"
         exit 1
     fi
 }
 
 Kubernetes_patch
 
-
-function private_validate() {
-  if [ -f "$SAVE_PATH" ]; then
-      echo "File Downloaded."
-  else
-      echo "Failed to download"
-      exit 1
-  fi
- }
 
 
 
